### ISSUE TITLE
TC-08 Support

### ISSUE THREAD

**Issue by slightlynybbled** [picotech/picosdk-python-wrappers#10]
### Setup

* Example filename: none
* Version of Python: 3.7
* Pico Technology device model: TC-08
* Driver name, version number and platform (32- or 64-bit): 64-bit
* Operating system: Windows 10
* USB port type (e.g. 2.0): 2.0

### Description

Cannot find documentation or implementation for the TC-08 thermocouple reader.

#### Steps to reproduce the issue

Searching through the `picosdk-python-wrappers` repository.

#### Actual Result

No instances of the `tc-08`, `tc08`, `TC08`, `TC-08`, etc. found.

#### Expected Result

Was hoping to find a `Tc08` wrapper object.

### Notes

None

**Comment by neil-hamilton** [comment]
We currently don't have support for the TC-08 within this repo but we will be looking to add it too the repo in the future

**Comment by Robimoo** [comment]
I am also interested in a Python support for the TC-08. Is it likely to become available this year ?

Thanks

**Comment by slightlynybbled** [comment]
Until there is decent support from the manufacturer, I was forced to go elsewhere in the interest of time.

The [DATAQ DI-2008](https://www.dataq.com/products/di-2008/) has similar capabilities and the ability to connect as a COM port, making connection to it from Python very simple.  I went with that since it was in a similar price range and was much easier to automate.
