### ISSUE TITLE
Merge conflict indicators in SigGen example files

### ISSUE THREAD

**Issue by TheCoconutChef** [picotech/picosdk-python-wrappers#11]
There are merge conflict indicators in ps2000aSigGen.py, ps5000aSigGen.py, ps6000SigGen.py and ps6000SigGen.py in the master branch of this repo.

Example in ps5000aSigGen.py:

```
<<<<<<< HEAD
# increment = 5
# dwellTime = 1
# sweepType = ctypes.c_int16(1) = PS5000A_UP
# operation = 0
# shots = 0
# sweeps = 0
=======
# increment = 5 kHz
# dwellTime = 1
# sweepType = ctypes.c_int16(1) = PS5000A_UP
# operation = 0
# shots = 0
# sweeps = 0
>>>>>>> 5e0135f9d98cbcc52b3e67336ed1873ba93cd40c
```

**Comment by neil-hamilton** [comment]
Issue resolved in https://github.com/picotech/picosdk-python-wrappers/commit/fefe1d87e556ed6c8b536e275044a4a2b48b2d61
