### ISSUE TITLE
Install through pip

### ISSUE THREAD

**Issue by Lorac** [picotech/picosdk-python-wrappers#3]
To install the wrappers inside my virtual environment I would like to do `pip3 install picosdk`.

**Comment by hsmistry** [comment]
Hi @Lorac, our files are not yet hosted on PyPI. I believe it is planned.

**Comment by Lorac** [comment]
@hsmistry Do you any news on this?

**Comment by hsmistry** [comment]
@Lorac, I'll check on this and provide an update

**Comment by Lorac** [comment]
There is no plan to add it to pypi? It's really annoying to not be able to add the package to a requirements.txt and pin the dependency to a version.
