### ISSUE TITLE
UnknownConstantError should subclass ValueError.

### ISSUE THREAD

**Issue by hardkrash** [picotech/picosdk-python-wrappers#5]
https://github.com/picotech/picosdk-python-wrappers/blob/e8deec9aafec96e102d96e40ee05b562f6fba529/picosdk/constants.py#L12

Custom exceptions can add great value, but when making these custom exception type please ensure that you base the exception on an appropriate base class.

**Comment by hardkrash** [comment]
There are other examples of this in other files. 
e.g.
https://github.com/picotech/picosdk-python-wrappers/blob/e8deec9aafec96e102d96e40ee05b562f6fba529/picosdk/device.py#L17-L22

These probably deserve to have a base class as PicoScopeError or some other inheritance tree.
This way one can 

```python
try:
    scope.do_something()
except PicoScopeError:
    print("The turboencabulator is broken, look at the semi-lunar shaft couplers.")
except Exception:
    logger.traceback("I blew up unexpectedly.")
    test_state = "Oh no!"
finally:
    shut_down_test()
```

**Comment by hsmistry** [comment]
@hardkrash, thanks for reporting this. I will put this forward for review.

**Comment by neil-hamilton** [comment]
Hi

We have updated the repository now and have added custom exceptions
