### ISSUE TITLE
Trouble setting up ETS mode 2205A

### ISSUE THREAD

**Issue by AntonyLHart** [picotech/picosdk-python-wrappers#7]
### Setup

* Example filename: Autotest ETS Problem (manipulated version of ps2000BlockExample)
* Version of Python: 3 (running code in idle)
* Pico Technology device model 2205A:
* Driver name, version number and platform (32- or 64-bit): libps2000
* Operating system: Raspbian stretch
* USB port type	(e.g. 2.0): 2.0

### Description
In attempt to capture a better representation of the signal I am attempting to invoke the ETS block mode. I have successfully run the normal block mode in a loop, but I am looking for something a little cleaner. I was hoping you might have a look at my code and see if you can help out a little. 

#### Steps to reproduce the issue

Currently, the program dies at the point shown below, and the shell restarts. 

    # Get times and values
            status["getTimesAndValues"] = ps.ps2000_get_times_and_values(chandle,
                                                                         ctypes.byref(times), # time interval between trigger and 
    sample
                                                                         ctypes.byref(bufferA), # pointer to data buffer
                                                                         ctypes.byref(bufferB), # pointer to data buffer
                                                                         None, # bufferC not used
                                                                         None, # bufferD not used
                                                                         0, # ChA overflow
                                                                         2, # time_units (ns)
                                                                         maxSamples) # no_of_values #SHELL RESTART HERE
            assert_pico2000_ok(status["getTimesAndValues"])      

Use one of two methods to describe the issue:

I feel as though I am pretty close to getting this to work the way I intend. Can't work out whats going on here. Need a fresh pair of eyes if you don't mind? 
[Autotest_ETS_Problem.txt](https://github.com/picotech/picosdk-python-wrappers/files/2543580/Autotest_ETS_Problem.txt)

**Comment by hsmistry** [comment]
Hi @AntonyLHart, for the overflow parameter, please try passing a value using ctypes.byref as it is a pointer to a value.

If that does not work, try the same code on a Windows or Linux (e.g. Ubuntu) system. It will help to narrow down if it is an issue in the code or driver.

**Comment by AntonyLHart** [comment]
There doesn't seem to be a definition for _get_times_and_values in library.py. I think this iss why the prgram crashes upon excecution of the class call. Do you know if there is any work being done here? Where is the best place to put in a request. I don't think this is something I'm going to be able to do myself. Bit of a show stopper atm. Can't get ets mode running without _get_times_and_values. 
Any advise here?

**Comment by AntonyLHart** [comment]
Latest version of application attached
[Autotest_ETS_Problem.txt](https://github.com/picotech/picosdk-python-wrappers/files/2552989/Autotest_ETS_Problem.txt)

**Comment by AntonyLHart** [comment]
I have made a change to the overflow parameter as you can see in the code. I actually realised this also and made the change, however, it doesn't seem to be that, which is crashing the application.

**Comment by hsmistry** [comment]
Thanks @AntonyLHart. A member of the team is looking into this so we'll provide an update as soon as we can.

**Comment by AntonyLHart** [comment]
that's good news, thanks for the assistance. I'll be looking forward to the update

**Comment by AntonyLHart** [comment]
Can any one shed any light as to the origin of the problem?

**Comment by hsmistry** [comment]
Hi @AntonyLHart, does the function crash if you do not use ETS mode?

Have you tried the same code on a Windows or Linux PC?

**Comment by AntonyLHart** [comment]
No, not yet. I'll get to it. I was wondering if anyone has looked at the driver .py's yet? Particularly library.py. I haven't had any problems with any existing examples so it seems strange that it would be something to do with the raspberry pie, or debian. I cannot find anyone who has attempted the ETS mode. I will aim to run this on another system, not that I have one to hand. Can you tell me if there have been **ANY** successful implementations of ETS mode coded in python on linux?

**Comment by AntonyLHart** [comment]
And yes, If I do not setup ETS mode, the function still crashes

**Comment by hsmistry** [comment]
Hi @AntonyLHart, the definition of the function is in ps2000.py as it is a ctypes function in a shared library.

I have requested for this to be investigated as a matter of priority.

**Comment by AntonyLHart** [comment]
OK thanks

**Comment by AntonyLHart** [comment]
Any news here?

**Comment by neil-hamilton** [comment]
Hi @AntonyLHart would you be able to try the attached ETS example and see if it runs on your system

[ps2000ETSBlockExample.txt](https://github.com/picotech/picosdk-python-wrappers/files/2652881/ps2000ETSBlockExample.txt)
